services:
  - type: web
    name: ai-video-detector
    env: docker
    plan: standard
    healthCheckPath: /healthz
    autoDeploy: false
    envVars:
      - key: VERSION
        value: "1.2.3"
      - key: ALLOWED_ORIGINS
        value: "https://www.greensovereignfund.ch,https://greensovereignfund.ch"
      - key: MAX_UPLOAD_BYTES
        value: "52428800"           # 50 MB
      - key: RESOLVER_MAX_BYTES
        value: "125829120"          # 120 MB
      - key: REQUEST_TIMEOUT_S
        value: "180"
      - key: USE_YTDLP
        value: "1"
      - key: RESOLVER_UA
        value: "Mozilla/5.0 (AVD/1.2; +https://www.greensovereignfund.ch)"
      - key: YTDLP_OPTS
        value: '{"noplaylist":true,"continuedl":false,"retries":1}'
      - key: THRESH_REAL_MAX
        value: "0.35"
      - key: THRESH_AI_MIN
        value: "0.72"