services:
  - type: web
    name: ai-video-detector
    env: docker
    plan: free
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: ALLOWED_ORIGINS
        sync: false
      - key: MAX_UPLOAD_BYTES
        value: "52428800"
      - key: RESOLVER_MAX_BYTES
        value: "125829120"
      - key: REQUEST_TIMEOUT_S
        value: "120"
      - key: USE_YTDLP
        value: "1"
      - key: RESOLVER_UA
        value: "Mozilla/5.0 (AVD/1.0; +https://ai-video.org)"
      - key: YTDLP_OPTS
        value: '{"noplaylist":true,"continuedl":false,"retries":1}'
