services:
  - type: web
    name: ai-video-detector
    env: docker
    plan: starter
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: MAX_UPLOAD_BYTES
        value: "52428800"
      - key: REQUEST_TIMEOUT_S
        value: "240"
      - key: USE_YTDLP
        value: "0"
