services:
  - type: web
    name: ai-video-detector
    env: docker
    plan: starter
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      # CORS / Frontend
      - key: FRONTEND_ORIGIN
        value: "https://greensovereignfund.ch"
      - key: ALLOWED_ORIGINS
        value: "https://greensovereignfund.ch,https://www.greensovereignfund.ch"

      # Limiti/timeout
      - key: MAX_UPLOAD_BYTES
        value: "52428800"   # 50MB
      - key: RESOLVER_MAX_BYTES
        value: "125829120"  # 120MB
      - key: CONNECT_TIMEOUT
        value: "6.0"
      - key: READ_TIMEOUT
        value: "15.0"

      # Resolver Social (opzionale)
      - key: USE_YTDLP
        value: "0"          # metti "1" se vuoi attivare yt-dlp
      - key: YTDLP_COOKIES
        value: ""           # es: /app/cookies.txt se monti cookie

      # Gunicorn
      - key: WEB_CONCURRENCY
        value: "2"
      - key: WORKER_TIMEOUT
        value: "120"